export const projects = [
  {
    title: 'CS2103 SWE Project [In progress]',
    description: "Written in Java. Libraries used: JavaFX, Jackson, JSON In Java, opencsv, JUnit", 
      image: '/images/Ui1_v1.3.1.png',
      tags: ['Java', 'JavaFx', 'Junit', 'Json', 'opencsv'],
    source: 'https://github.com/AY2122S1-CS2103-F09-3/tp',
    visit: 'https://github.com/AY2122S1-CS2103-F09-3/tp',
    id: 0,
  },
  {
    title: 'LifeHack 2021 MediaTe [Hackathon- 2nd Prize]',
    description:"Ever wondered how technology will revolutionise our education and social interactions? Mediate, Media to Educate, enables people to generate AI videos with faces given text and a video with a face!",
    image: '/images/lifehack.png',
    tags: ['aws', 'aws-lambda', 'react', 'vercel'],
    source: ' mediate.vercel.app',
    visit: 'https://devpost.com/software/mediate-bouafk?ref_content=user-portfolio&ref_feature=in_progress',
    id: 1,
  },
  {
    title: 'Duke Chatbot',
    description: "Duke, a Personal Assistant Chatbot aims to help a person to keep track of various things.",
      image: '/images/ip.png',
      tags: ['Java', 'JavaFx', 'Junit', 'Chatbot'], 
    source: 'https://github.com/erwinqxy/ip',
    visit: 'https://erwinqxy.github.io/ip/',
    id: 2,
  },
  {
    title: 'My Study buddy [NUS Orbital 2021]',
    description: "Aim: A platform that allows NUS students to come together to create a more conducive environment while providing an engaging experience in light of the pandemic.",
    image: '/images/orbital.png',
    tags: ['Python', 'Django', 'html', 'Javascript', 'css', 'heroku'],
    source: 'https://www.youtube.com/watch?v=f47M37MsqGI&ab_channel=NUSOrbital',
    visit: 'http://msbud.herokuapp.com/',
    id: 3,
  },
  {
    title: 'CodeEXP 2021 Foodome [Hackathon]',
    description: "A React Native mobile app for home-based businesses in Singapore to market their products to consumers. Users will not only be able to make purchases with those who live within their neighbourhood (Neighbourhood Buy) but also optionally facilitate deliveries to those in their group (Neighbourhood Delivery).",
    image: '/images/foodome.png',
    tags: ['React', 'React', 'Mobile App'],
    source: 'https://github.com/AllardQuek/Foodome',
    visit: 'https://youtu.be/HBTLbBTkt0M',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Grew an interest in programming', },
  { year: 2019, text: 'Matriculated into School of Computing in National Singapore', },
  { year: 2021, text: 'Embarked on Orbital-Apollo11 Project', },
  { year: 2021, text: 'Participated in DSTA CodeEXP hackathon', },
  { year: 2021, text: 'Participated in NUS LifeHack 2021 [2nd Prize]', },
];